[package]
name = "atrium-daemon"
version = "0.1.0"
edition = "2021"
default-run = "atriumd"

[[bin]]
name = "atriumd"
path = "src/main.rs"

[dependencies]
atrium-core-graph = { path = "../atrium-core-graph" }
atrium-core-memory = { path = "../atrium-core-memory" }
atrium-core-verify = { path = "../atrium-core-verify" }

tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
rust-embed = "8.3.0"
axum = { version = "0.6.20" }
mime_guess = "2.0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-stream = "0.3"
futures-util = "0.3"

[build-dependencies]
tonic-build = { workspace = true }
